### ISSUE TITLE
Adding additional dense layers for differential ATAC

### ISSUE THREAD

**Issue by snaqvi1990** [BernsteinLab/BE_CD69_paper_2022#1]
Hi, thanks for making detailed code available. I would like to do something similar to what was done in your paper, but instead of having three dense layers replacing the cell-type/organism-specific heads, I would like to have eleven dense layers (6 different ATAC datasets, and then 5 differential tracks comparing each of the 5 targets to the reference). Where would the code to do this be? Presumably it is somewhere in enformer_ft_train.py but I can't figure out where.

Thanks in advance,
Sahin

**Comment by naumanjaved** [comment]
Hi,

Thanks for your message. Re-organizing the fine tuning code to make this easier is on my to do list but for now: 

1. You would need to organize all your tracks into the required format using the [basenji](https://github.com/calico/basenji) suite. That repository has instructions for how to process coverage tracks (in your case, normalized bigwigs) into the required tensorflow records format for Enformer. You will need the train/test/validation intervals, which are provided as bed files in the basenji bucket(gs://basenji_barnyard/data, provided as 131072 bp intervals and need to be padded to 196608bp), as well as targets file (example [here](https://raw.githubusercontent.com/calico/basenji/master/manuscripts/cross2020/targets_human.txt). For the differential tracks, the normalization is critical (in our paper we opted for RPGC but there may be better options) and you will have to clip negatives. 

2. You would need to change the number of output heads in the main model file (unfortunately currently hard-coded) here:
https://github.com/BernsteinLab/BE_CD69_paper_2022/blob/751080d6b78902dc67dcbcfa392dae4d2b850a02/enformer_fine_tuning/enformer.py#L154-L156

3. Set the appropriate number of `heads` in the execute_sweep.sh bash script, which is passed through in the enformer_ft_train.py script to the deserialize_tr function, where the tensorflow records from step 1 are deserialized

4. Change the logging in enformer_ft_train.py to track the relevant metrics (i.e. correlations for each cell-type):
https://github.com/BernsteinLab/BE_CD69_paper_2022/blob/751080d6b78902dc67dcbcfa392dae4d2b850a02/enformer_fine_tuning/enformer_ft_train.py#L262-L265

Hope this helps
Nauman

**Comment by snaqvi1990** [comment]
Hi Nauman,

Great, thanks so much for this detailed information! Right now I just have one question about item 1. For the differential tracks, what does it mean by “clip negatives”? If the track is log2 of the ratio, won’t all the regions that are down in one cell type relative to the reference be clipped to 0 and not be recognized as changed? Does this mean only one direction of change at a time can be predicted?

Thanks,
Sahin

**Comment by naumanjaved** [comment]
Hi Sahin,

My apologies for the late reply on this. Yes - the idea was to just predict the change in one direction, though there isn't a particularly strong reason to do this. If you want to predict both directions, you would have to change the final activation layer (currently set at softplus which has a strictly positive output) to allow prediction of negative targets.

Nauman
